### ISSUE TITLE
Discrepancy between altitude & pressure in yocto_msg and node internals

### ISSUE THREAD

**Issue by gavanderhoorn** [amstrudy/yoctopuce_altimeter#2]
The `yocto_msg` currently uses `float64` (C++ `double`) for the `altitude` and `pressure` fields:

https://github.com/amstrudy/yoctopuce_altimeter/blob/30cb30831e3702e572deaad25dbc269392dce3a9/msg/yocto_msg.msg#L3-L4

while the node itself uses `float` ([ROS msg](http://wiki.ros.org/msg) `float32`) to store new altitude and pressure readings coming from the sensor:

https://github.com/amstrudy/yoctopuce_altimeter/blob/30cb30831e3702e572deaad25dbc269392dce3a9/src/altimeter_publisher.cpp#L57-L58

The Yocto API seems to suggest that the returned value for at least the pressure is a double ([here](https://github.com/amstrudy/yoctopuce_altimeter/blob/30cb30831e3702e572deaad25dbc269392dce3a9/include/yocto/yocto_api/yocto_altitude.h#L141)).

It would be good not to coerce it into a `float` as that may cause loss of precision.

**Comment by amstrudy** [comment]
Thank you for the note. I can't seem to use a double in my msg declaration, though.

All of these cause errors which are immediately resolved when I change the type back to `float64`:
`double altitude # m`
`double64 altitude # m`
`double32 altitude # m`

I guess my question is: how are doubles declared in ros msg headers?

**Comment by anja-sheppard** [comment]
Fixed via this commit.
https://github.com/amstrudy/yoctopuce_altimeter/commit/e33b3c05bd93514dc6b3246028fe84cec1bc60b4

**Comment by gavanderhoorn** [comment]
Seems like we can close this then.
